### ISSUE TITLE
This role is not compatible with Python 3

### ISSUE THREAD

**Issue by aciguru** [datacenter/ansible-role-aci-model#4]
This role has been configured to run on python 2 and is not compatible with python 3.

**Comment by dagwieers** [comment]
If you report an issue, could you please state the issue, what you did, what you expected, etc.
We can make this role work on Python 3, but for that I need to know exactly what it is about.

**Comment by dagwieers** [comment]
If you report an issue, could you please state the issue, what you did, what you expected, etc.
We can make this role work on Python 3, but for that I need to know exactly what it is about.

**Comment by aciguru** [comment]
While running this sample ansible role, I encountered an error while running the playbook. The error was a traceback error as shown below:

TASK [datacenter.aci-model : include_tasks] **************************************************************************************************************************************
task path: /Users/apoorvagururaja/ansible/datacenter.aci-model/tasks/main.yml:2
included: /Users/apoorvagururaja/ansible/datacenter.aci-model/tasks/main-json.yml for apic1
ERROR! Unexpected Exception, this is probably a bug: 'dict' object has no attribute 'iteritems'
the full traceback was:

Traceback (most recent call last):
  File "/Users/apoorvagururaja/ansible/bin/ansible-playbook", line 111, in <module>
    exit_code = cli.run()
  File "/Users/apoorvagururaja/ansible/lib/ansible/cli/playbook.py", line 121, in run
    results = pbex.run()
  File "/Users/apoorvagururaja/ansible/lib/ansible/executor/playbook_executor.py", line 170, in run
    result = self._tqm.run(play=play)
  File "/Users/apoorvagururaja/ansible/lib/ansible/executor/task_queue_manager.py", line 239, in run
    play_return = strategy.run(iterator, play_context)
  File "/Users/apoorvagururaja/ansible/lib/ansible/plugins/strategy/linear.py", line 278, in run
    task_vars = self._variable_manager.get_vars(play=iterator._play, host=host, task=task)
  File "/Users/apoorvagururaja/ansible/lib/ansible/vars/manager.py", line 419, in get_vars
    all_vars['ansible_delegated_vars'], all_vars['_ansible_loop_cache'] = self._get_delegated_vars(play, task, all_vars)
  File "/Users/apoorvagururaja/ansible/lib/ansible/vars/manager.py", line 509, in _get_delegated_vars
    loader=self._loader, fail_on_undefined=True, convert_bare=False)
  File "/Users/apoorvagururaja/ansible/lib/ansible/utils/listify.py", line 33, in listify_lookup_plugin_terms
    terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
  File "/Users/apoorvagururaja/ansible/lib/ansible/template/__init__.py", line 538, in template
    disable_lookups=disable_lookups,
  File "/Users/apoorvagururaja/ansible/lib/ansible/template/__init__.py", line 803, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/Users/apoorvagururaja/ansible/datacenter.aci-model/plugins/filter/aci.py", line 8, in listify
    return listify_worker(d, keys, 0, [], {}, '')
  File "/Users/apoorvagururaja/ansible/datacenter.aci-model/plugins/filter/aci.py", line 17, in listify_worker
    for k,v in item.iteritems():

AttributeError: 'dict' object has no attribute 'iteritems'

Please allow flexibility to run in Python 3. A quick fix I did was changing iteritems() to items() in the aci.py file.

**Comment by devarshishah3** [comment]
fixed issue

**Comment by devarshishah3** [comment]
fixed issue
